version: '3.8'

services:
  confluence-tool:
    build: .
    ports:
      - "8005:8005"
    environment:
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      - CHROMA_PERSIST_DIRECTORY=/app/chroma
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      - API_HOST=0.0.0.0
      - API_PORT=8005
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - chroma_data:/app/chroma
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - confluence-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - confluence-tool
    networks:
      - confluence-network
    profiles:
      - production

volumes:
  chroma_data:
    driver: local

networks:
  confluence-network:
    driver: bridge